# Generated by Django 4.1.5 on 2023-02-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название организации')),
                ('bank_details', models.TextField(verbose_name='Банковские реквизиты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('volume', models.FloatField(verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер стеллажа')),
                ('storage_capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('max_load', models.FloatField(verbose_name='Максимальная нагрузка')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.room', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Стеллаж',
                'verbose_name_plural': 'Стеллажи',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления')),
                ('contract_number', models.PositiveIntegerField(verbose_name='Номер договора')),
                ('contract_end_date', models.DateField(verbose_name='Дата окончания договора')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.client', verbose_name='Клиент')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.shelf', verbose_name='Стеллаж')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['height'],
            },
        ),
    ]
